config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get 'early_access', to: 'pages#early_access'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  mount ActiveAnalytics::Engine, at: "analytics"

  # resources :waiting_users, only: [:create]
  # resources :trial_click_users, only: [:create]
  resources :search_preferences, only: [:new, :create] do
    get 'results', on: :collection
    get 'post', on: :collection
    get 'company', on: :collection
    post 'company_submit', on: :collection
  end

  resources :resources, param: :id

  post 'emails', to: 'pages#submit_email'
  resources :generate_posts
  get 'download', to: 'generate_posts#download'
end

app/models/generate_post.rb
class GeneratePost < ApplicationRecord
  belongs_to :mail_list, optional: true
end

app/controllers/generate_posts_controller.rb
class GeneratePostsController < ApplicationController
  def index
    @images = GeneratePost.all
  end
  def create
    @generate_post = GeneratePost.new(generate_post_params)
    # @image = stability(@generate_post)
    # @image = post
    sleep 8

    respond_to do |format|
      if @generate_post.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.update(:results, partial: "generated",
            locals: { image: @image, post: @generate_post }, status: :accepted)
        end
        # format.html { redirect_to generate_posts_url}
        # format.html { render partial: 'generated' }
        # format.json { render json: @generate_post, status: :created }
        # format.js   # Render a JavaScript response (used for AJAX)
      else
        format.html { render :new }
        format.json { render json: @generate_post.errors, status: :unprocessable_entity }
        format.js   { render :errors } # Create a partial for displaying errors via JavaScript
      end
    end

  end

  def post
    image_path = ActionController::Base.helpers.asset_path('favicon2.svg')
    html_content =
      "<html>
        <body>
          <div class=\"element\">
            <div class=\"element-x\">
                <p class=\"how-to-develop-a\">-HOW TO DEVELOP A STARTUPPERS MINDSET &amp; NOTICE IDEAS AROUND YOU?</p>
                <div class=\"text-wrapper\">Interview</div>
                <div class=\"div\">John Wain</div>
                <div class=\"text-wrapper-2\">EMOJI IMG</div>
                <div class=\"group\">
                    <img class=\"img\" src=\"#{image_path}\" alt=\"Image Description\">
                </div>
            </div>
          </div>
        </body>
      </html>"


    @kit = IMGKit.new(html_content)
    @kit.stylesheets << '/home/mikececco/rails-newsjack/app/assets/stylesheets/search_preferences/_new.scss'

    image_path = 'public/images/image.png'
    @kit.to_file(image_path)

    # Now you can pass the image path to your view
    image_path
  end

  def stability(input)
    # @input = input
    # # Set the API token
    # api_token = ENV["STABILITY_KEY"]

    # # Define the request parameters
    # url = URI.parse('https://api.replicate.com/v1/predictions')
    # headers = { 'Content-Type' => 'application/json', 'Authorization' => "Token #{api_token}" }
    # data = {
    #   version: '8beff3369e81422112d93b89ca01426147de542cd4684c244b673b105188fe5f',
    #   input: {
    #     prompt: "Giraffe with black skin"
    #   }
    # }

    # # Send the POST request
    # http = Net::HTTP.new(url.host, url.port)
    # http.use_ssl = true
    # request = Net::HTTP::Post.new(url.path, headers)
    # request.body = data.to_json
    # response = http.request(request)

    # unless response.is_a?(Net::HTTPSuccess)
    #   raise StandardError, "HTTP request failed with status code #{response.code}. Response body: #{response.body}"
    # end

    # puts "Response code: #{response.code}"
    # puts "Response body: #{response.body}"

    # # Extract the response id
    # if response.code == '200' || response.code == '201'
    #   parsed_response = JSON.parse(response.body)
    #   prediction_id = parsed_response['id']

    #   # Make a GET request to get the response based on the id
    #   response_url = "https://api.replicate.com/v1/predictions/#{prediction_id}"
    #   response_request = Net::HTTP::Get.new(response_url, 'Authorization' => "Token #{api_token}")
    #   response = http.request(response_request)

    #   # Print the response
    #   response_hash = JSON.parse(response.body)
    #   output_url = response_hash['output'] # Assuming 'output' is an array with one URL

    #   puts "OUTPUT URUL #{output_url}"

    # # Check if output_url is nil and assign a default URL if needed
    #   output_url = 'https://pbxt.replicate.delivery/mx7Jb91MfwzPZSCgMjC5CpKbRpX2B0bEu4UD6LaxfT9rWOoRA/out-0.png' if output_url.nil?
    # else
    #   output_url = 'https://pbxt.replicate.delivery/R51v7QaXfMTJdibt0IO56BObyFeCAtwQ1rqhjJJLke5Me3gGB/out-0.png'
    # end
    output_url = 'https://pbxt.replicate.delivery/R51v7QaXfMTJdibt0IO56BObyFeCAtwQ1rqhjJJLke5Me3gGB/out-0.png'
    output_url
  end

  def download
    image_filename = 'image.jpeg'
    image_path = Rails.root.join('app', 'assets', 'images', image_filename)

    send_file image_path, filename: image_filename, type: 'image/jpeg'
  end

  private

  def generate_post_params
    params.require(:generate_post).permit(:company_website_url, :trend, :social_media_url, :topic)
  end
end

app/views/generate_posts/_generated.html.erb
<div class="align-middle">
  <p class="mb-2">
    Content will be sent within 2 hours by email
  </p>
  <%= render 'shared/sign_button', post: post %>
</div>

app/views/generate_posts/_generatedLive.html.erb
<div class="align-middle">
  <div class="progress-wrapper w-75 mx-auto">
    <div class="progress-info">
      <div class="progress-percentage">
        <span class="text-xs font-weight-bold">Trending: 87%</span>
      </div>
    </div>
    <div class="progress">
      <div class="progress-bar bg-gradient-primary w-80" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
  </div>
  <div class="progress-wrapper w-75 mx-auto">
    <div class="progress-info">
      <div class="progress-percentage">
        <span class="text-xs font-weight-bold">Brand affinity: 93%</span>
      </div>
    </div>
    <div class="progress">
      <div class="progress-bar bg-gradient-secondary w-90" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
  </div>
  <div class="progress-wrapper w-75 mx-auto">
    <div class="progress-info">
      <div class="progress-percentage">
        <span class="text-xs font-weight-bold">Potential impressions: 5~12k</span>
      </div>
    </div>
    <div class="progress">
      <div class="progress-bar bg-gradient-info w-90" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
  </div>
  <div class="progress-wrapper w-75 mx-auto">
    <div class="progress-info">
      <div class="progress-percentage">
        <span class="text-xs font-weight-bold">Timeframe: <span id="timer">17h</span></span>
      </div>
    </div>
    <div class="progress">
      <div class="progress-bar bg-gradient-warning w-15" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
  </div>
</div>
<div class="mt-3">
  <p>Just like Lionel Messi's Balon d'Or win, Ginzo sushi restaurant sets the standard for excellence.
  Here is how we make our sushi 🧵 <br>
  <%= image_tag "image.jpeg", alt: "Image generated", class: "d-block mx-lg-auto img-fluid", width:"300", height:"200", loading:"lazy" %>
  Prepare the Rice:<br>

  Start with short-grain sushi rice.
  Rinse the rice until the water runs clear.
  Cook the rice according to package instructions.
  Mix sushi vinegar (rice vinegar, sugar, and salt) into the cooked rice while it's still warm. This gives the rice its characteristic flavor and stickiness.
  Assemble the Sushi:
    <%= image_tag "image1.jpeg", alt: "Image generated", class: "d-block mx-lg-auto img-fluid", width:"150", height:"100", loading:"lazy" %>

  <br>
  Place a bamboo sushi rolling mat on a clean surface.
  Lay a sheet of plastic wrap on the mat to prevent sticking.
  Put a sheet of nori (seaweed) on the plastic wrap, shiny side down.
  Moisten your fingers to prevent sticking and spread a thin layer of prepared rice evenly over the nori, leaving a small border at the top.
  Add your choice of ingredients like sliced fish, vegetables, or avocado on top of the rice.
  Roll and Slice:
    <%= image_tag "image2.jpeg", alt: "Image generated", class: "d-block mx-lg-auto img-fluid", width:"150", height:"100", loading:"lazy" %>
  <br>
  Lift the bamboo mat's edge closest to you and start rolling the nori and rice over the fillings, using the mat to shape it into a tight cylinder.
  Wet the exposed border of the nori with a bit of water to seal the roll.
  Use a sharp, wet knife to slice the roll into bite-sized pieces. Dip the knife in water between cuts to prevent sticking.
  Serve your homemade sushi with soy sauce, pickled ginger, and wasabi. Enjoy your delicious creations! 🍣 #SushiMaking #HomemadeSushi #SushiChef

  </p>

  <%= link_to "Regenerate", download_path, class: "btn btn-outline-primary px-3 py-2 w-full rounded-4" %>
  <%= link_to "Tweet 🐦", download_path, id: "tweet", class: "btn btn-primary text-white px-3 py-2 w-full rounded-4 border border-info" %>


  <ul class="mt-5">
    More newsjacked posts are also ready!
    <li><a>Trending: Fortnite</a></li>
    <li>
      <a>Incoming trend: Black Friday</a>
    </li>
    <li>
      <a>Incoming trend: Christmas</a>
    </li>
    <li>
      <a>Trending: Japan autumn</a>
    </li>
  </ul>
  <%# <%= image
  <%= post.trend
  # Your content will be sent within 2hours to your email
  # <%= render 'shared/sign_button' %>
</div>

app/views/generate_posts/create.js.erb
<% if @generate_post.errors.any? %>
  // Handle errors, for example by updating a DOM element with error messages
  alert('Error: ' + '<%= j @generate_post.errors.full_messages.join(', ') %>');
<% else %>
  // Handle success, for example by updating a DOM element with a success message
  alert('Post created successfully!');
<% end %>