config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get 'early_access', to: 'pages#early_access'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  mount ActiveAnalytics::Engine, at: "analytics"

  # resources :waiting_users, only: [:create]
  # resources :trial_click_users, only: [:create]
  resources :search_preferences, only: [:new, :create] do
    get 'results', on: :collection
    get 'post', on: :collection
    get 'company', on: :collection
    post 'company_submit', on: :collection
  end

  resources :resources, param: :id

  post 'emails', to: 'pages#submit_email'
  resources :generate_posts
  get 'download', to: 'generate_posts#download'
end

app/views/resources/index.html.erb
<% content_for :title, "NewsJack resources" %>
<% content_for :meta_description, "Empower your brand with NewsJack — Seamlessly match trends, harness AI, and generate engaging content. Elevate your brand's presence effortlessly" %>

<main>
 <section class="container py-5 mt-5">
    <%= render 'shared/back' %>
    <div>
        <div class="row">
            <div class="col-xl-12 text-center pb-3">
                <div class="section-title service-title">
                  <h1 class="fw-bold text-center m-0 bigger">Resources</h1>
                </div>
            </div>
        </div>
        <div class="row">
          <% @resources.each do |resource| %>
            <div class="col-xl-4 col-lg-4 col-md-6">
              <a href="<%= resource_path(resource) %>" class="text-black text-decoration-none">
                <div class="blog-wrapper home-blog-wrapper white-bg nice-round mb-5">
                  <div class="blog-content home-blog text-center">
                    <h2 class="blog-title text-center">
                      <%= resource.title %>
                    </h2>
                    <p>
                      <% truncated_content = truncate(strip_tags(resource.content), length: 100) %>
                      <%= markdown(truncated_content) %>
                    </p>
                  </div>
                  <div class="link-box home-blog-link">
                    <h2><%= link_to "Read More", resource_path(resource) %></h2>
                  </div>
                </div>
              </a>
            </div>
          <% end %>
        </div>
    </div>
</section>

app/views/resources/new.html.erb
<main class="container py-5 mt-5">
  <div>
    <%= simple_form_for @resource do |f| %>
      <%= f.input :title %>
      <%= f.input :content, as: :text, input_html: { rows: 10 } %>
      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</main>

app/views/resources/show.html.erb
<% content_for :title, "#{@resource.title} - Blog" %>
<% truncated_content = truncate(strip_tags(@resource.content), length: 250) %>
<% content_for :meta_description, markdown(truncated_content) %>


<main class="container py-5 mt-5">
  <div class="row">
    <div class="col-12">
      <%= render 'shared/back' %>
    </div>
  </div>
  <div class="py-5 mt-5 px-3">
    <h1 class="fw-bold text-center m-0 bigger"><%= @resource.title %></h1>
    <p class="text-center px-3"><%= markdown(@resource.content) %></p>
  </div>
</main>