config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get 'early_access', to: 'pages#early_access'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  mount ActiveAnalytics::Engine, at: "analytics"

  # resources :waiting_users, only: [:create]
  # resources :trial_click_users, only: [:create]
  resources :search_preferences, only: [:new, :create] do
    get 'results', on: :collection
    get 'post', on: :collection
    get 'company', on: :collection
    post 'company_submit', on: :collection
  end

  resources :resources, param: :id

  post 'emails', to: 'pages#submit_email'
  resources :generate_posts
  get 'download', to: 'generate_posts#download'
end

app/models/search_preference.rb
class SearchPreference < ApplicationRecord
  belongs_to :scraper
end

app/controllers/search_preferences_controller.rb
require 'uri'
require 'net/http'
require 'json'

class SearchPreferencesController < ApplicationController
  def new
    if Rails.env.production? && request.location.present?
      @country = request.location.country_code
    else
      # Set a default country for non-production environments
      @country = 'US' # Or any default country code you prefer
    end
    @search_preference = SearchPreference.new
  end

  def create
    @search_preference = SearchPreference.new(search_preference_params)
    @scraper = Scraper.new
    @search_preference.scraper = @scraper
    if @search_preference.save
      country = ISO3166::Country[@search_preference.country_code]
      readable_country = country.translations[I18n.locale.to_s]
      current_time = Time.now

      # Format the current time in the desired format
      formatted_timestamp = current_time.strftime('%Y-%m-%d %H:%M:%S.%N000 %z')

      # Convert the timestamp to a DateTime object
      timestamp_datetime = DateTime.parse(formatted_timestamp)

      # Calculate the start and end of the day for the given timestamp
      start_of_day = timestamp_datetime.beginning_of_day
      end_of_day = timestamp_datetime.end_of_day
      today_search_preference = SearchPreference.find_by(country_code: @search_preference.country_code, created_at: start_of_day..end_of_day)

      current_date = Time.now.strftime('%Y-%m-%d')
      scraper_cache_key = "scraper_#{@search_preference.country_code}_#{current_date}"

      cached_scraper = Rails.cache.read(scraper_cache_key)
      if today_search_preference && cached_scraper.present?
        @scraper = cached_scraper[:scraper]
        @twitter_trends = cached_scraper[:twitter_trends]
      else
        @scraper.country_code = @search_preference.country_code
        @scraper.country_name = @scraper.set_country(@search_preference.country_code)
        @scraper.scraped_news = @scraper.start
        @scraper.search_preference = @search_preference
        @scraper.save
        @twitter_trends = twitter_trends

        cache_data = {
          scraper: @scraper,
          twitter_trends: @twitter_trends
        }

        Rails.cache.write(scraper_cache_key, cache_data, expires_in: 24.hours)
      end

      redirect_to results_search_preferences_path(google_scraped: @scraper, twitter: @twitter_trends.to_json)
    else
      render :new
    end
  end

  def results
    @twitter_trends = JSON.parse(params[:twitter])
    @scraped_news = Scraper.find(params[:google_scraped])
    string = @scraped_news.scraped_news
    @hash_with_title = eval(string)
    @title = @hash_with_title.delete(:title)
    @new_hash = @hash_with_title.dup
    @to_ask = []
    @new_hash.each do |index, news_item|
      @to_ask << (news_item[:translated] == nil ? news_item[:news] : news_item[:translated])
    end
    @image = stability
    # SHOULD TRIGGER A CHATGPT CALL TO just SKIM the suitable trends, 3, to the brands identity
  end

  def twitter_trends
    url = URI("https://twitter-trends5.p.rapidapi.com/twitter/request.php")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true

    request = Net::HTTP::Post.new(url)
    request["content-type"] = 'application/x-www-form-urlencoded'
    request["X-RapidAPI-Key"] = ENV["RAPID_KEY"]
    request["X-RapidAPI-Host"] = 'twitter-trends5.p.rapidapi.com'

    world = "woeid=1"
    us = "woeid=23424977"
    request.body = world #to be CHANGED TO THE REQUESTED COUNTRY INPUT

    response = http.request(request)
    trying = response.read_body

    response_dict = JSON.parse(trying)

    data = response_dict["trends"]

    # Extract "name" and "volume" attributes from each hash
    name_volume_list = []
    @display = []
    data.each do |key, value|
      name = value["name"]
      volume = value["volume"]
      @display << [name, volume]
      name_volume_list << { "name" => name, "volume" => volume }
    end

    # Specify the file name
    file_name = "name_volume.json"

    # Convert the list to JSON format
    json_data = JSON.pretty_generate(name_volume_list)

    # Write the JSON data to the file
    File.open(file_name, "w") do |file|
      file.write(json_data)
    end

    @display
    #SELECT WOEID
    # @world_trends = TwitterTrends.new(1)
    # world_trends_data = @world_trends.fetch_trends
    # world_data = world_trends.extract_data(world_trends_data)
    # world_trends.save_to_json(world_data, "world_name_volume.json")
  end

  def stability
    # Set the API token
    api_token = ENV["STABILITY_KEY"]

    # Define the request parameters
    url = URI.parse('https://api.replicate.com/v1/predictions')
    headers = { 'Content-Type' => 'application/json', 'Authorization' => "Token #{api_token}" }
    data = {
      version: '8beff3369e81422112d93b89ca01426147de542cd4684c244b673b105188fe5f',
      input: {
        prompt: "An illustration of an avocado sitting in a therapist's chair, saying 'I just feel so empty inside' with a pit-sized hole in its center. The therapist, a spoon, scribbles notes."
      }
    }

    # Send the POST request
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    request = Net::HTTP::Post.new(url.path, headers)
    request.body = data.to_json
    response = http.request(request)

    # Extract the response id
    if response.code == '200' || response.code == '201'
      parsed_response = JSON.parse(response.body)
      prediction_id = parsed_response['id']

      # Make a GET request to get the response based on the id
      response_url = "https://api.replicate.com/v1/predictions/#{prediction_id}"
      response_request = Net::HTTP::Get.new(response_url, 'Authorization' => "Token #{api_token}")
      response = http.request(response_request)

      # Print the response
      response_hash = JSON.parse(response.body)
      output_url = response_hash['output'] # Assuming 'output' is an array with one URL

      output_url = response_hash['output']

    # Check if output_url is nil and assign a default URL if needed
      output_url = 'https://pbxt.replicate.delivery/mx7Jb91MfwzPZSCgMjC5CpKbRpX2B0bEu4UD6LaxfT9rWOoRA/out-0.png' if output_url.nil?
    else
      output_url = 'https://pbxt.replicate.delivery/R51v7QaXfMTJdibt0IO56BObyFeCAtwQ1rqhjJJLke5Me3gGB/out-0.png'
    end
    output_url
  end

    # def create
    #   redirect_to company_search_preferences_path
    # end

  # def results
  # end

  def company
  end

  def company_submit
    redirect_to results_search_preferences_path
  end

  def post

  end

  private

  def search_preference_params
    params.require(:search_preference).permit(:country_code)
  end
end

app/views/search_preferences/_navbar.html.erb
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" navbar-scroll="true">
      <div class="container-fluid py-1 px-0">
        <nav aria-label="breadcrumb">
          <%# <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Dashboard</li>
          </ol> %>
          <%# <h6 class="font-weight-bolder mb-0">Dashboard</h6> %>
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 d-flex justify-content-between" id="navbar">
            <ul class="navbar-nav">
              <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                  <div class="sidenav-toggler-inner">
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                  </div>
                </a>
              </li>
            </ul>
            <ul class="navbar-nav justify-content-end">
              <li class="nav-item d-flex align-items-center">
                <%# <a class="btn btn-outline-primary btn-sm mb-0 me-3" target="_blank" href="https://www.creative-tim.com/builder?ref=navbar-soft-ui-dashboard">Generate Post</a> %>
              </li>
              <li class="nav-item d-flex align-items-center">
                <a href="javascript:;" class="nav-link text-body font-weight-bold px-0">
                  <%# <i class="fa fa-user me-sm-1"></i> %>
                  <span class="d-sm-inline d-none text-white">Sign In</span>
                </a>
              </li>
              <%# <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                  <div class="sidenav-toggler-inner">
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                  </div>
                </a>
              </li> %>
            </ul>
        </div>
      </div>
    </nav>

app/views/search_preferences/_sidebar.html.erb
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 " id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0 text-center">
        <%# <img src="../assets/img/logo-ct-dark.png" class="navbar-brand-img h-100" alt="main_logo"> %>
        <%= image_tag 'favicon2.svg', class: 'navbar-brand-img h-100' %>
        <span class="ms-1 font-weight-bold">NewsJack</span>
      </a>
    </div>
    <hr class="horizontal dark mt-0">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="<%= new_search_preference_path %>">
            <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
              <svg width="12px" height="12px" viewBox="0 0 45 40" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <title>shop </title>
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <g transform="translate(-1716.000000, -439.000000)" fill="#FFFFFF" fill-rule="nonzero">
                    <g transform="translate(1716.000000, 291.000000)">
                      <g transform="translate(0.000000, 148.000000)">
                        <path class="color-background opacity-6" d="M46.7199583,10.7414583 L40.8449583,0.949791667 C40.4909749,0.360605034 39.8540131,0 39.1666667,0 L7.83333333,0 C7.1459869,0 6.50902508,0.360605034 6.15504167,0.949791667 L0.280041667,10.7414583 C0.0969176761,11.0460037 -1.23209662e-05,11.3946378 -1.23209662e-05,11.75 C-0.00758042603,16.0663731 3.48367543,19.5725301 7.80004167,19.5833333 L7.81570833,19.5833333 C9.75003686,19.5882688 11.6168794,18.8726691 13.0522917,17.5760417 C16.0171492,20.2556967 20.5292675,20.2556967 23.494125,17.5760417 C26.4604562,20.2616016 30.9794188,20.2616016 33.94575,17.5760417 C36.2421905,19.6477597 39.5441143,20.1708521 42.3684437,18.9103691 C45.1927731,17.649886 47.0084685,14.8428276 47.0000295,11.75 C47.0000295,11.3946378 46.9030823,11.0460037 46.7199583,10.7414583 Z"></path>
                        <path class="color-background" d="M39.198,22.4912623 C37.3776246,22.4928106 35.5817531,22.0149171 33.951625,21.0951667 L33.92225,21.1107282 C31.1430221,22.6838032 27.9255001,22.9318916 24.9844167,21.7998837 C24.4750389,21.605469 23.9777983,21.3722567 23.4960833,21.1018359 L23.4745417,21.1129513 C20.6961809,22.6871153 17.4786145,22.9344611 14.5386667,21.7998837 C14.029926,21.6054643 13.533337,21.3722507 13.0522917,21.1018359 C11.4250962,22.0190609 9.63246555,22.4947009 7.81570833,22.4912623 C7.16510551,22.4842162 6.51607673,22.4173045 5.875,22.2911849 L5.875,44.7220845 C5.875,45.9498589 6.7517757,46.9451667 7.83333333,46.9451667 L19.5833333,46.9451667 L19.5833333,33.6066734 L27.4166667,33.6066734 L27.4166667,46.9451667 L39.1666667,46.9451667 C40.2482243,46.9451667 41.125,45.9498589 41.125,44.7220845 L41.125,22.2822926 C40.4887822,22.4116582 39.8442868,22.4815492 39.198,22.4912623 Z"></path>
                      </g>
                    </g>
                  </g>
                </g>
              </svg>
            </div>
            <span class="nav-link-text me-1">Generate post</span>
          </a>
        </li>
        <%# <li class="nav-item">
          <a class="nav-link disabled" href="<%= results_search_preferences_path">
            <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
              <svg width="12px" height="12px" viewBox="0 0 42 42" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <title>office</title>
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <g transform="translate(-1869.000000, -293.000000)" fill="#FFFFFF" fill-rule="nonzero">
                    <g transform="translate(1716.000000, 291.000000)">
                      <g id="office" transform="translate(153.000000, 2.000000)">
                        <path class="color-background opacity-6" d="M12.25,17.5 L8.75,17.5 L8.75,1.75 C8.75,0.78225 9.53225,0 10.5,0 L31.5,0 C32.46775,0 33.25,0.78225 33.25,1.75 L33.25,12.25 L29.75,12.25 L29.75,3.5 L12.25,3.5 L12.25,17.5 Z"></path>
                        <path class="color-background" d="M40.25,14 L24.5,14 C23.53225,14 22.75,14.78225 22.75,15.75 L22.75,38.5 L19.25,38.5 L19.25,22.75 C19.25,21.78225 18.46775,21 17.5,21 L1.75,21 C0.78225,21 0,21.78225 0,22.75 L0,40.25 C0,41.21775 0.78225,42 1.75,42 L40.25,42 C41.21775,42 42,41.21775 42,40.25 L42,15.75 C42,14.78225 41.21775,14 40.25,14 Z M12.25,36.75 L7,36.75 L7,33.25 L12.25,33.25 L12.25,36.75 Z M12.25,29.75 L7,29.75 L7,26.25 L12.25,26.25 L12.25,29.75 Z M35,36.75 L29.75,36.75 L29.75,33.25 L35,33.25 L35,36.75 Z M35,29.75 L29.75,29.75 L29.75,26.25 L35,26.25 L35,29.75 Z M35,22.75 L29.75,22.75 L29.75,19.25 L35,19.25 L35,22.75 Z"></path>
                      </g>
                    </g>
                  </g>
                </g>
              </svg>
            </div>
            <span class="nav-link-text ms-1">Ideas generator</span>
          </a>
        </li> %>
        <%# <li class="nav-item mt-3">
          <h6 class="ps-4 ms-2 text-uppercase text-xs font-weight-bolder opacity-6">Account pages</h6>
        </li>
        <li class="nav-item">
          <a class="nav-link  " href="../pages/profile.html">
            <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
              <svg width="12px" height="12px" viewBox="0 0 46 42" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <title>customer-support</title>
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <g transform="translate(-1717.000000, -291.000000)" fill="#FFFFFF" fill-rule="nonzero">
                    <g transform="translate(1716.000000, 291.000000)">
                      <g transform="translate(1.000000, 0.000000)">
                        <path class="color-background opacity-6" d="M45,0 L26,0 C25.447,0 25,0.447 25,1 L25,20 C25,20.379 25.214,20.725 25.553,20.895 C25.694,20.965 25.848,21 26,21 C26.212,21 26.424,20.933 26.6,20.8 L34.333,15 L45,15 C45.553,15 46,14.553 46,14 L46,1 C46,0.447 45.553,0 45,0 Z"></path>
                        <path class="color-background" d="M22.883,32.86 C20.761,32.012 17.324,31 13,31 C8.676,31 5.239,32.012 3.116,32.86 C1.224,33.619 0,35.438 0,37.494 L0,41 C0,41.553 0.447,42 1,42 L25,42 C25.553,42 26,41.553 26,41 L26,37.494 C26,35.438 24.776,33.619 22.883,32.86 Z"></path>
                        <path class="color-background" d="M13,28 C17.432,28 21,22.529 21,18 C21,13.589 17.411,10 13,10 C8.589,10 5,13.589 5,18 C5,22.529 8.568,28 13,28 Z"></path>
                      </g>
                    </g>
                  </g>
                </g>
              </svg>
            </div>
            <span class="nav-link-text ms-1">Profile</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link  " href="../pages/sign-in.html">
            <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
              <svg width="12px" height="12px" viewBox="0 0 40 44" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <title>document</title>
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <g transform="translate(-1870.000000, -591.000000)" fill="#FFFFFF" fill-rule="nonzero">
                    <g transform="translate(1716.000000, 291.000000)">
                      <g transform="translate(154.000000, 300.000000)">
                        <path class="color-background opacity-6" d="M40,40 L36.3636364,40 L36.3636364,3.63636364 L5.45454545,3.63636364 L5.45454545,0 L38.1818182,0 C39.1854545,0 40,0.814545455 40,1.81818182 L40,40 Z"></path>
                        <path class="color-background" d="M30.9090909,7.27272727 L1.81818182,7.27272727 C0.814545455,7.27272727 0,8.08727273 0,9.09090909 L0,41.8181818 C0,42.8218182 0.814545455,43.6363636 1.81818182,43.6363636 L30.9090909,43.6363636 C31.9127273,43.6363636 32.7272727,42.8218182 32.7272727,41.8181818 L32.7272727,9.09090909 C32.7272727,8.08727273 31.9127273,7.27272727 30.9090909,7.27272727 Z M18.1818182,34.5454545 L7.27272727,34.5454545 L7.27272727,30.9090909 L18.1818182,30.9090909 L18.1818182,34.5454545 Z M25.4545455,27.2727273 L7.27272727,27.2727273 L7.27272727,23.6363636 L25.4545455,23.6363636 L25.4545455,27.2727273 Z M25.4545455,20 L7.27272727,20 L7.27272727,16.3636364 L25.4545455,16.3636364 L25.4545455,20 Z"></path>
                      </g>
                    </g>
                  </g>
                </g>
              </svg>
            </div>
            <span class="nav-link-text ms-1">Sign In</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link  " href="../pages/sign-up.html">
            <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
              <svg width="12px" height="20px" viewBox="0 0 40 40" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <title>spaceship</title>
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <g transform="translate(-1720.000000, -592.000000)" fill="#FFFFFF" fill-rule="nonzero">
                    <g transform="translate(1716.000000, 291.000000)">
                      <g transform="translate(4.000000, 301.000000)">
                        <path class="color-background" d="M39.3,0.706666667 C38.9660984,0.370464027 38.5048767,0.192278529 38.0316667,0.216666667 C14.6516667,1.43666667 6.015,22.2633333 5.93166667,22.4733333 C5.68236407,23.0926189 5.82664679,23.8009159 6.29833333,24.2733333 L15.7266667,33.7016667 C16.2013871,34.1756798 16.9140329,34.3188658 17.535,34.065 C17.7433333,33.98 38.4583333,25.2466667 39.7816667,1.97666667 C39.8087196,1.50414529 39.6335979,1.04240574 39.3,0.706666667 Z M25.69,19.0233333 C24.7367525,19.9768687 23.3029475,20.2622391 22.0572426,19.7463614 C20.8115377,19.2304837 19.9992882,18.0149658 19.9992882,16.6666667 C19.9992882,15.3183676 20.8115377,14.1028496 22.0572426,13.5869719 C23.3029475,13.0710943 24.7367525,13.3564646 25.69,14.31 C26.9912731,15.6116662 26.9912731,17.7216672 25.69,19.0233333 L25.69,19.0233333 Z"></path>
                        <path class="color-background opacity-6" d="M1.855,31.4066667 C3.05106558,30.2024182 4.79973884,29.7296005 6.43969145,30.1670277 C8.07964407,30.6044549 9.36054508,31.8853559 9.7979723,33.5253085 C10.2353995,35.1652612 9.76258177,36.9139344 8.55833333,38.11 C6.70666667,39.9616667 0,40 0,40 C0,40 0,33.2566667 1.855,31.4066667 Z"></path>
                        <path class="color-background opacity-6" d="M17.2616667,3.90166667 C12.4943643,3.07192755 7.62174065,4.61673894 4.20333333,8.04166667 C3.31200265,8.94126033 2.53706177,9.94913142 1.89666667,11.0416667 C1.5109569,11.6966059 1.61721591,12.5295394 2.155,13.0666667 L5.47,16.3833333 C8.55036617,11.4946947 12.5559074,7.25476565 17.2616667,3.90166667 L17.2616667,3.90166667 Z"></path>
                        <path class="color-background opacity-6" d="M36.0983333,22.7383333 C36.9280725,27.5056357 35.3832611,32.3782594 31.9583333,35.7966667 C31.0587397,36.6879974 30.0508686,37.4629382 28.9583333,38.1033333 C28.3033941,38.4890431 27.4704606,38.3827841 26.9333333,37.845 L23.6166667,34.53 C28.5053053,31.4496338 32.7452344,27.4440926 36.0983333,22.7383333 L36.0983333,22.7383333 Z"></path>
                      </g>
                    </g>
                  </g>
                </g>
              </svg>
            </div>
            <span class="nav-link-text ms-1">Sign Up</span>
          </a>
        </li> %>
      </ul>
    </div>
  </aside>

app/views/search_preferences/company.html.erb
<main class="container py-5 mt-5 vh-100">
  <div class="row">
    <div class="col-12">
      <%= render 'shared/back' %>
    </div>
  </div>
  <div class="container py-5 mt-5 px-3">
    <div class="row justify-content-center align-items-center">
      <div class="col-lg-6">
        <form action="<%= company_submit_search_preferences_path %>" method="post">
          <div class="text-center mb-4">
            <h1 class="h3 mb-3 fw-normal">Describe your company</h1>
          </div>
          <div class="mb-3 text-center">
            <textarea rows="2" cols="40" class="form-control"></textarea>
          </div>
          <div class="form-actions text-center">
            <input type="submit" value="Submit" class="custom-link btn btn-lg text-white bg-primary rounded-pill border border-warning d-inline-flex align-items-center justify-content-center">
          </div>
        </form>
      </div>
    </div>
  </div>
</main>

app/views/search_preferences/new.html.erb
<body class="g-sidenav-show  bg-gray-100">
  <%= render 'sidebar' %>

  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">

    <%= render 'navbar' %>

    <turbo-frame id="box_1" data-turbo-action="advance">
      <div class="container-fluid py-4">
        <div class="row my-4" data-controller="generate">
          <div class="col-lg-8 col-md-6 mb-md-0 mb-4">
            <div class="card">
              <div class="card-header pb-0">
                <div class="row">
                  <div class="col-lg-6 col-7">
                    <h6>Select country</h6>
                  </div>
                </div>
              </div>
              <div class="container py-5 px-3">
                <div class="row justify-content-center align-items-center">
                  <div class="col-lg-6">
                    <div class="d-flex justify-content-center">
                      <div class="spinner-border mb-3" id="loading-bar" role="status">
                        <span class="visually-hidden">Loading...</span>
                      </div>
                    </div>
                    <%= simple_form_for @search_preference, html: { id: 'search-preference-form' } do |f| %>

                      <div class="text-center mb-4">
                        <p>Detected country:<span class="badge text-black fst-italic"> <%= @country %></span></p>
                      </div>
                      <div class="mb-3">
                        <%= f.country_select :country_code, { priority_countries: [@country] }, { label: false, class: 'form-control' } %>
                      </div>
                      <div class="form-actions text-center">
                        <%= f.button :button, type: "submit", class: 'text-white bg-primary px-3 py-2 w-full rounded-4 border border-warning' do %>
                          Select
                        <% end %>
                        <%# <progress id="content-loading-bar" class="loading-bar" value="0" data-turbo-permanent></progress> %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
    </turbo-frame>
  </main>
</body>

app/views/search_preferences/post.html.erb
<main class="container py-5 mt-5">
  <%= render 'shared/logo' %>
  <%= render 'shared/back' %>
  <h1 class="h3 mb-3 fw-normal">NewsJacked content generated for you</h1>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="card text-center col-md-4 mt-3 col-sm-10 p-0">
      <div class="card-header p-0">
        <%= image_tag 'avocado-square.png', class: 'w-100', loading:'lazy'%>
        <div class="card-body">
          <h3 class="card-title">How to get your avocado treatment?</h3>
          <p class="card-text">To be, or not to be: that is the question: whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune, or to take arms against a sea of troubles, and by opposing end them? To die: to sleep; no more; and, by a sleep to say we end the heart-ache and the thousand natural shocks that flesh is heir to, 'tis a consummation devoutly to be wish'd. To die, to sleep; to sleep: perchance to dream: ay, there's the rub; for in that sleep of death what dreams may come when we have shuffled off this mortal coil, must give us pause. </p>
          <span class="badge badge-pill bg-black">Twitter</span>
          <span class="badge badge-pill bg-primary">LinkedIn</span>
        </div>
      </div>
  	</div>
  </div>
</main>